#This script makes a semicolon character string with all municipalities in each county.
#These strings must in turn be used manually copied and pasted into
#the Excel sheet norspis_units_keyfigures_minuscontacts.xlsx in extdata folder.

#From:https://www.regjeringen.no/no/tema/kommuner-og-regioner/kommunereform/nye-kommuner/id2470015/
# I have used the addin DATAPASTA to paste this:
kommuner2020 <- tibble::tribble(
  ~Nummer,                     ~Kommunenavn,
  "0301",                           "Oslo",
  "1101",                      "Eigersund",
  "1103",                      "Stavanger",
  "1106",                      "Haugesund",
  "1108",                        "Sandnes",
  "1111",                        "Sokndal",
  "1112",                           "Lund",
  "1114",                      "Bjerkreim",
  "1119",                             "Hå",
  "1120",                          "Klepp",
  "1121",                           "Time",
  "1122",                        "Gjesdal",
  "1124",                           "Sola",
  "1127",                      "Randaberg",
  "1130",                         "Strand",
  "1133",                     "Hjelmeland",
  "1134",                         "Suldal",
  "1135",                          "Sauda",
  "1144",                        "Kvitsøy",
  "1145",                           "Bokn",
  "1146",                         "Tysvær",
  "1149",                         "Karmøy",
  "1151",                         "Utsira",
  "1160",                     "Vindafjord",
  "1505",                   "Kristiansund",
  "1506",                          "Molde",
  "1507",                        "Ålesund",
  "1511",                       "Vanylven",
  "1514",                          "Sande",
  "1515",               "Herøy (M. og R.)",
  "1516",                        "Ulstein",
  "1517",                         "Hareid",
  "1520",                          "Ørsta",
  "1525",                        "Stranda",
  "1528",                      "Sykkylven",
  "1531",                           "Sula",
  "1532",                          "Giske",
  "1535",                        "Vestnes",
  "1539",                          "Rauma",
  "1547",                          "Aukra",
  "1554",                         "Averøy",
  "1557",                        "Gjemnes",
  "1560",                       "Tingvoll",
  "1563",                        "Sunndal",
  "1566",                       "Surnadal",
  "1573",                          "Smøla",
  "1576",                           "Aure",
  "1577",                          "Volda",
  "1578",                          "Fjord",
  "1579",                     "Hustadvika",
  "1804",                           "Bodø",
  "1806",                         "Narvik",
  "1811",                         "Bindal",
  "1812",                          "Sømna",
  "1813",                        "Brønnøy",
  "1815",                           "Vega",
  "1816",                      "Vevelstad",
  "1818",                 "Herøy (Nordl.)",
  "1820",                      "Alstahaug",
  "1822",                      "Leirfjord",
  "1824",                          "Vefsn",
  "1825",                          "Grane",
  "1826",                   "Hattfjelldal",
  "1827",                          "Dønna",
  "1828",                          "Nesna",
  "1832",                         "Hemnes",
  "1833",                           "Rana",
  "1834",                          "Lurøy",
  "1835",                          "Træna",
  "1836",                          "Rødøy",
  "1837",                          "Meløy",
  "1838",                      "Gildeskål",
  "1839",                         "Beiarn",
  "1840",                        "Saltdal",
  "1841",                 "Fauske-Fuossko",
  "1845",                        "Sørfold",
  "1848",                        "Steigen",
  "1851",                       "Lødingen",
  "1853",                         "Evenes",
  "1856",                           "Røst",
  "1857",                          "Værøy",
  "1859",                       "Flakstad",
  "1860",                      "Vestvågøy",
  "1865",                          "Vågan",
  "1866",                         "Hadsel",
  "1867",                             "Bø",
  "1868",                         "Øksnes",
  "1870",                       "Sortland",
  "1871",                          "Andøy",
  "1874",                       "Moskenes",
  "1875",                        "Hamarøy",
  "3001",                         "Halden",
  "3002",                           "Moss",
  "3003",                      "Sarpsborg",
  "3004",                    "Fredrikstad",
  "3005",                        "Drammen",
  "3006",                      "Kongsberg",
  "3007",                      "Ringerike",
  "3011",                         "Hvaler",
  "3012",                        "Aremark",
  "3013",                         "Marker",
  "3014",                  "Indre Østfold",
  "3015",                       "Skiptvet",
  "3016",                      "Rakkestad",
  "3017",                           "Råde",
  "3018",                  "Våler (Østf.)",
  "3019",                         "Vestby",
  "3020",                   "Nordre Follo",
  "3021",                             "Ås",
  "3022",                          "Frogn",
  "3023",                       "Nesodden",
  "3024",                          "Bærum",
  "3025",                          "Asker",
  "3026",                 "Aurskog-Høland",
  "3027",                       "Rælingen",
  "3028",                        "Enebakk",
  "3029",                      "Lørenskog",
  "3030",                     "Lillestrøm",
  "3031",                       "Nittedal",
  "3032",                       "Gjerdrum",
  "3033",                     "Ullensaker",
  "3034",                            "Nes",
  "3035",                       "Eidsvoll",
  "3036",                      "Nannestad",
  "3037",                         "Hurdal",
  "3038",                           "Hole",
  "3039",                            "Flå",
  "3040",                        "Nesbyen",
  "3041",                            "Gol",
  "3042",                       "Hemsedal",
  "3043",                             "Ål",
  "3044",                            "Hol",
  "3045",                         "Sigdal",
  "3046",                     "Krødsherad",
  "3047",                          "Modum",
  "3048",                     "Øvre Eiker",
  "3049",                           "Lier",
  "3050",                       "Flesberg",
  "3051",                         "Rollag",
  "3052",                  "Nore og Uvdal",
  "3053",                       "Jevnaker",
  "3054",                         "Lunner",
  "3401",                    "Kongsvinger",
  "3403",                          "Hamar",
  "3405",                    "Lillehammer",
  "3407",                         "Gjøvik",
  "3411",                      "Ringsaker",
  "3412",                          "Løten",
  "3413",                         "Stange",
  "3414",                      "Nord-Odal",
  "3415",                       "Sør-Odal",
  "3416",                        "Eidskog",
  "3417",                           "Grue",
  "3418",                          "Åsnes",
  "3419",                  "Våler (Hedm.)",
  "3420",                        "Elverum",
  "3421",                         "Trysil",
  "3422",                           "Åmot",
  "3423",                    "Stor-Elvdal",
  "3424",                       "Rendalen",
  "3425",                       "Engerdal",
  "3426",                          "Tolga",
  "3427",                         "Tynset",
  "3428",                         "Alvdal",
  "3429",                        "Folldal",
  "3430",                             "Os",
  "3431",                          "Dovre",
  "3432",                          "Lesja",
  "3433",                          "Skjåk",
  "3434",                            "Lom",
  "3435",                           "Vågå",
  "3436",                      "Nord-Fron",
  "3437",                            "Sel",
  "3438",                       "Sør-Fron",
  "3439",                        "Ringebu",
  "3440",                           "Øyer",
  "3441",                        "Gausdal",
  "3442",                    "Østre Toten",
  "3443",                   "Vestre Toten",
  "3446",                           "Gran",
  "3447",                    "Søndre Land",
  "3448",                    "Nordre Land",
  "3449",                     "Sør-Aurdal",
  "3450",                        "Etnedal",
  "3451",                    "Nord-Aurdal",
  "3452",                  "Vestre Slidre",
  "3453",                  "Øystre Slidre",
  "3454",                           "Vang",
  "3801",                         "Horten",
  "3802",                    "Holmestrand",
  "3803",                       "Tønsberg",
  "3804",                     "Sandefjord",
  "3805",                         "Larvik",
  "3806",                      "Porsgrunn",
  "3807",                          "Skien",
  "3808",                       "Notodden",
  "3811",                         "Færder",
  "3812",                         "Siljan",
  "3813",                         "Bamble",
  "3814",                        "Kragerø",
  "3815",                      "Drangedal",
  "3816",                           "Nome",
  "3817",                  "Midt-Telemark",
  "3818",                           "Tinn",
  "3819",                       "Hjartdal",
  "3820",                        "Seljord",
  "3821",                      "Kviteseid",
  "3822",                       "Nissedal",
  "3823",                       "Fyresdal",
  "3824",                          "Tokke",
  "3825",                          "Vinje",
  "4201",                          "Risør",
  "4202",                       "Grimstad",
  "4203",                        "Arendal",
  "4204",                   "Kristiansand",
  "4205",                      "Lindesnes",
  "4206",                        "Farsund",
  "4207",                    "Flekkefjord",
  "4211",                       "Gjerstad",
  "4212",                      "Vegårshei",
  "4213",                    "Tvedestrand",
  "4214",                        "Froland",
  "4215",                      "Lillesand",
  "4216",                       "Birkenes",
  "4217",                           "Åmli",
  "4218",                        "Iveland",
  "4219",                "Evje og Hornnes",
  "4220",                        "Bygland",
  "4221",                          "Valle",
  "4222",                          "Bykle",
  "4223",                       "Vennesla",
  "4224",                         "Åseral",
  "4225",                        "Lyngdal",
  "4226",                     "Hægebostad",
  "4227",                      "Kvinesdal",
  "4228",                         "Sirdal",
  "4601",                         "Bergen",
  "4602",                           "Kinn",
  "4611",                           "Etne",
  "4612",                          "Sveio",
  "4613",                          "Bømlo",
  "4614",                          "Stord",
  "4615",                         "Fitjar",
  "4616",                         "Tysnes",
  "4617",                     "Kvinnherad",
  "4618",                     "Ullensvang",
  "4619",                       "Eidfjord",
  "4620",                          "Ulvik",
  "4621",                           "Voss",
  "4622",                           "Kvam",
  "4623",                      "Samnanger",
  "4624",                  "Bjørnafjorden",
  "4625",                      "Austevoll",
  "4626",                       "Øygarden",
  "4627",                          "Askøy",
  "4628",                        "Vaksdal",
  "4629",                        "Modalen",
  "4630",                        "Osterøy",
  "4631",                          "Alver",
  "4632",                      "Austrheim",
  "4633",                          "Fedje",
  "4634",                     "Masfjorden",
  "4635",                          "Gulen",
  "4636",                         "Solund",
  "4637",                      "Hyllestad",
  "4638",                       "Høyanger",
  "4639",                            "Vik",
  "4640",                        "Sogndal",
  "4641",                        "Aurland",
  "4642",                         "Lærdal",
  "4643",                          "Årdal",
  "4644",                         "Luster",
  "4645",                        "Askvoll",
  "4646",                         "Fjaler",
  "4647",                      "Sunnfjord",
  "4648",                      "Bremanger",
  "4649",                           "Stad",
  "4650",                        "Gloppen",
  "4651",                          "Stryn",
  "5001",                      "Trondheim",
  "5006",                      "Steinkjer",
  "5007",                         "Namsos",
  "5014",                          "Frøya",
  "5020",                           "Osen",
  "5021",                         "Oppdal",
  "5022",                        "Rennebu",
  "5025",                          "Røros",
  "5026",                       "Holtålen",
  "5027",                 "Midtre Gauldal",
  "5028",                         "Melhus",
  "5029",                          "Skaun",
  "5031",                         "Malvik",
  "5032",                          "Selbu",
  "5033",                          "Tydal",
  "5034",                        "Meråker",
  "5035",                       "Stjørdal",
  "5036",                         "Frosta",
  "5037",                       "Levanger",
  "5038",                         "Verdal",
  "5041",                   "Snåase-Snåsa",
  "5042",                         "Lierne",
  "5043",            "Raarvihke - Røyrvik",
  "5044",                     "Namsskogan",
  "5045",                          "Grong",
  "5046",                      "Høylandet",
  "5047",                      "Overhalla",
  "5049",                      "Flatanger",
  "5052",                           "Leka",
  "5053",                        "Inderøy",
  "5054",                    "Indre Fosen",
  "5055",                           "Heim",
  "5056",                          "Hitra",
  "5057",                         "Ørland",
  "5058",                         "Åfjord",
  "5059",                        "Orkland",
  "5060",                      "Nærøysund",
  "5061",                         "Rindal",
  "5401",                         "Tromsø",
  "5402",             "Harstad - Hárstták",
  "5403",                           "Alta",
  "5404",                          "Vardø",
  "5405",                          "Vadsø",
  "5406",                     "Hammerfest",
  "5411",                       "Kvæfjord",
  "5412",                      "Tjeldsund",
  "5413",                        "Ibestad",
  "5414",                      "Gratangen",
  "5415",              "Loabák - Lavangen",
  "5416",                          "Bardu",
  "5417",                       "Salangen",
  "5418",                        "Målselv",
  "5419",                       "Sørreisa",
  "5420",                          "Dyrøy",
  "5421",                          "Senja",
  "5422",                      "Balsfjord",
  "5423",                        "Karlsøy",
  "5424",                         "Lyngen",
  "5425", "Storfjord-Omasvuotna-Omasvuono",
  "5426",     "Gáivuotna-Kåfjord-Kaivuono",
  "5427",                       "Skjervøy",
  "5428",                      "Nordreisa",
  "5429",                      "Kvænangen",
  "5430",       "Guovdageaidnu-Kautokeino",
  "5432",                          "Loppa",
  "5433",                         "Hasvik",
  "5434",                          "Måsøy",
  "5435",                       "Nordkapp",
  "5436",   "Porsanger-Porsá?gu-Porsanki ",
  "5437",            "Kárášjohka-Karasjok",
  "5438",                        "Lebesby",
  "5439",                         "Gamvik",
  "5440",                       "Berlevåg",
  "5441",                    "Deatnu-Tana",
  "5442",                "Unjárga-Nesseby",
  "5443",                      "Båtsfjord",
  "5444",                   "Sør-Varanger"
)

#Fra Kartverket (https://www.kartverket.no/kommunereform/tekniske-endringer/kommune--og-regionsendringer-2020/)
# via Regjerningen (https://www.regjeringen.no/no/tema/kommuner-og-regioner/kommunereform/nyekommuneogfylkesnummer/id2629203/?expand=factbox2684595):

#Data is copied and pasted. I have only edited the two Herøy municipalities manually, since they,
#contrary to the two Våler municipalities, did not have a specificitation on which county they belonged to.
kommuner_fylker2020_raw <- tibble::tribble(
  ~Fylkesnr..2019,   ~Fylkesnavn.2019, ~Kommunenr..2019,    ~Kommunenavn.2019, ~Fylkesnr..2020,       ~Fylkesnavn.2020, ~Kommunenr..2020,   ~Kommunenavn.2020,
  "01",          "ØSTFOLD",           "0101",             "HALDEN",            "30",                "VIKEN",           "3001",            "HALDEN",
  "01",          "ØSTFOLD",           "0104",               "MOSS",            "30",                "VIKEN",           "3002",              "MOSS",
  "01",          "ØSTFOLD",           "0105",          "SARPSBORG",            "30",                "VIKEN",           "3003",         "SARPSBORG",
  "01",          "ØSTFOLD",           "0106",        "FREDRIKSTAD",            "30",                "VIKEN",           "3004",       "FREDRIKSTAD",
  "01",          "ØSTFOLD",           "0111",             "HVALER",            "30",                "VIKEN",           "3011",            "HVALER",
  "01",          "ØSTFOLD",           "0118",            "AREMARK",            "30",                "VIKEN",           "3012",           "AREMARK",
  "01",          "ØSTFOLD",           "0119",             "MARKER",            "30",                "VIKEN",           "3013",            "MARKER",
  "01",          "ØSTFOLD",           "0121",            "RØMSKOG",            "30",                "VIKEN",           "3026",    "AURSKOG-HØLAND",
  "01",          "ØSTFOLD",           "0122",           "TRØGSTAD",            "30",                "VIKEN",           "3014",     "INDRE ØSTFOLD",
  "01",          "ØSTFOLD",           "0123",          "SPYDEBERG",            "30",                "VIKEN",           "3014",     "INDRE ØSTFOLD",
  "01",          "ØSTFOLD",           "0124",              "ASKIM",            "30",                "VIKEN",           "3014",     "INDRE ØSTFOLD",
  "01",          "ØSTFOLD",           "0125",           "EIDSBERG",            "30",                "VIKEN",           "3014",     "INDRE ØSTFOLD",
  "01",          "ØSTFOLD",           "0127",           "SKIPTVET",            "30",                "VIKEN",           "3015",          "SKIPTVET",
  "01",          "ØSTFOLD",           "0128",          "RAKKESTAD",            "30",                "VIKEN",           "3016",         "RAKKESTAD",
  "01",          "ØSTFOLD",           "0135",               "RÅDE",            "30",                "VIKEN",           "3017",              "RÅDE",
  "01",          "ØSTFOLD",           "0136",              "RYGGE",            "30",                "VIKEN",           "3002",              "MOSS",
  "01",          "ØSTFOLD",           "0137",      "VÅLER (ØSTF.)",            "30",                "VIKEN",           "3018",     "VÅLER (VIKEN)",
  "01",          "ØSTFOLD",           "0138",              "HOBØL",            "30",                "VIKEN",           "3014",     "INDRE ØSTFOLD",
  "02",         "AKERSHUS",           "0211",             "VESTBY",            "30",                "VIKEN",           "3019",            "VESTBY",
  "02",         "AKERSHUS",           "0213",                "SKI",            "30",                "VIKEN",           "3020",      "NORDRE FOLLO",
  "02",         "AKERSHUS",           "0214",                 "ÅS",            "30",                "VIKEN",           "3021",                "ÅS",
  "02",         "AKERSHUS",           "0215",              "FROGN",            "30",                "VIKEN",           "3022",             "FROGN",
  "02",         "AKERSHUS",           "0216",           "NESODDEN",            "30",                "VIKEN",           "3023",          "NESODDEN",
  "02",         "AKERSHUS",           "0217",           "OPPEGÅRD",            "30",                "VIKEN",           "3020",      "NORDRE FOLLO",
  "02",         "AKERSHUS",           "0219",              "BÆRUM",            "30",                "VIKEN",           "3024",             "BÆRUM",
  "02",         "AKERSHUS",           "0220",              "ASKER",            "30",                "VIKEN",           "3025",             "ASKER",
  "02",         "AKERSHUS",           "0221",     "AURSKOG-HØLAND",            "30",                "VIKEN",           "3026",    "AURSKOG-HØLAND",
  "02",         "AKERSHUS",           "0226",              "SØRUM",            "30",                "VIKEN",           "3030",        "LILLESTRØM",
  "02",         "AKERSHUS",           "0227",                "FET",            "30",                "VIKEN",           "3030",        "LILLESTRØM",
  "02",         "AKERSHUS",           "0228",           "RÆLINGEN",            "30",                "VIKEN",           "3027",          "RÆLINGEN",
  "02",         "AKERSHUS",           "0229",            "ENEBAKK",            "30",                "VIKEN",           "3028",           "ENEBAKK",
  "02",         "AKERSHUS",           "0230",          "LØRENSKOG",            "30",                "VIKEN",           "3029",         "LØRENSKOG",
  "02",         "AKERSHUS",           "0231",            "SKEDSMO",            "30",                "VIKEN",           "3030",        "LILLESTRØM",
  "02",         "AKERSHUS",           "0233",           "NITTEDAL",            "30",                "VIKEN",           "3031",          "NITTEDAL",
  "02",         "AKERSHUS",           "0234",           "GJERDRUM",            "30",                "VIKEN",           "3032",          "GJERDRUM",
  "02",         "AKERSHUS",           "0235",         "ULLENSAKER",            "30",                "VIKEN",           "3033",        "ULLENSAKER",
  "02",         "AKERSHUS",           "0236",     "NES (AKERSHUS)",            "30",                "VIKEN",           "3034",               "NES",
  "02",         "AKERSHUS",           "0237",           "EIDSVOLL",            "30",                "VIKEN",           "3035",          "EIDSVOLL",
  "02",         "AKERSHUS",           "0238",          "NANNESTAD",            "30",                "VIKEN",           "3036",         "NANNESTAD",
  "02",         "AKERSHUS",           "0239",             "HURDAL",            "30",                "VIKEN",           "3037",            "HURDAL",
  "03",             "OSLO",           "0301",               "OSLO",            "03",                 "OSLO",           "0301",              "OSLO",
  "04",          "HEDMARK",           "0402",        "KONGSVINGER",            "34",            "INNLANDET",           "3401",       "KONGSVINGER",
  "04",          "HEDMARK",           "0403",              "HAMAR",            "34",            "INNLANDET",           "3403",             "HAMAR",
  "04",          "HEDMARK",           "0412",          "RINGSAKER",            "34",            "INNLANDET",           "3411",         "RINGSAKER",
  "04",          "HEDMARK",           "0415",              "LØTEN",            "34",            "INNLANDET",           "3412",             "LØTEN",
  "04",          "HEDMARK",           "0417",             "STANGE",            "34",            "INNLANDET",           "3413",            "STANGE",
  "04",          "HEDMARK",           "0418",          "NORD-ODAL",            "34",            "INNLANDET",           "3414",         "NORD-ODAL",
  "04",          "HEDMARK",           "0419",           "SØR-ODAL",            "34",            "INNLANDET",           "3415",          "SØR-ODAL",
  "04",          "HEDMARK",           "0420",            "EIDSKOG",            "34",            "INNLANDET",           "3416",           "EIDSKOG",
  "04",          "HEDMARK",           "0423",               "GRUE",            "34",            "INNLANDET",           "3417",              "GRUE",
  "04",          "HEDMARK",           "0425",              "ÅSNES",            "34",            "INNLANDET",           "3418",             "ÅSNES",
  "04",          "HEDMARK",           "0426",      "VÅLER (HEDM.)",            "34",            "INNLANDET",           "3419", "VÅLER (INNLANDET)",
  "04",          "HEDMARK",           "0427",            "ELVERUM",            "34",            "INNLANDET",           "3420",           "ELVERUM",
  "04",          "HEDMARK",           "0428",             "TRYSIL",            "34",            "INNLANDET",           "3421",            "TRYSIL",
  "04",          "HEDMARK",           "0429",               "ÅMOT",            "34",            "INNLANDET",           "3422",              "ÅMOT",
  "04",          "HEDMARK",           "0430",        "STOR-ELVDAL",            "34",            "INNLANDET",           "3423",       "STOR-ELVDAL",
  "04",          "HEDMARK",           "0432",           "RENDALEN",            "34",            "INNLANDET",           "3424",          "RENDALEN",
  "04",          "HEDMARK",           "0434",           "ENGERDAL",            "34",            "INNLANDET",           "3425",          "ENGERDAL",
  "04",          "HEDMARK",           "0436",              "TOLGA",            "34",            "INNLANDET",           "3426",             "TOLGA",
  "04",          "HEDMARK",           "0437",             "TYNSET",            "34",            "INNLANDET",           "3427",            "TYNSET",
  "04",          "HEDMARK",           "0438",             "ALVDAL",            "34",            "INNLANDET",           "3428",            "ALVDAL",
  "04",          "HEDMARK",           "0439",            "FOLLDAL",            "34",            "INNLANDET",           "3429",           "FOLLDAL",
  "04",          "HEDMARK",           "0441",         "OS (HEDM.)",            "34",            "INNLANDET",           "3430",    "OS (INNLANDET)",
  "05",          "OPPLAND",           "0501",        "LILLEHAMMER",            "34",            "INNLANDET",           "3405",       "LILLEHAMMER",
  "05",          "OPPLAND",           "0502",             "GJØVIK",            "34",            "INNLANDET",           "3407",            "GJØVIK",
  "05",          "OPPLAND",           "0511",              "DOVRE",            "34",            "INNLANDET",           "3431",             "DOVRE",
  "05",          "OPPLAND",           "0512",              "LESJA",            "34",            "INNLANDET",           "3432",             "LESJA",
  "05",          "OPPLAND",           "0513",              "SKJÅK",            "34",            "INNLANDET",           "3433",             "SKJÅK",
  "05",          "OPPLAND",           "0514",                "LOM",            "34",            "INNLANDET",           "3434",               "LOM",
  "05",          "OPPLAND",           "0515",               "VÅGÅ",            "34",            "INNLANDET",           "3435",              "VÅGÅ",
  "05",          "OPPLAND",           "0516",          "NORD-FRON",            "34",            "INNLANDET",           "3436",         "NORD-FRON",
  "05",          "OPPLAND",           "0517",                "SEL",            "34",            "INNLANDET",           "3437",               "SEL",
  "05",          "OPPLAND",           "0519",           "SØR-FRON",            "34",            "INNLANDET",           "3438",          "SØR-FRON",
  "05",          "OPPLAND",           "0520",            "RINGEBU",            "34",            "INNLANDET",           "3439",           "RINGEBU",
  "05",          "OPPLAND",           "0521",               "ØYER",            "34",            "INNLANDET",           "3440",              "ØYER",
  "05",          "OPPLAND",           "0522",            "GAUSDAL",            "34",            "INNLANDET",           "3441",           "GAUSDAL",
  "05",          "OPPLAND",           "0528",        "ØSTRE TOTEN",            "34",            "INNLANDET",           "3442",       "ØSTRE TOTEN",
  "05",          "OPPLAND",           "0529",       "VESTRE TOTEN",            "34",            "INNLANDET",           "3443",      "VESTRE TOTEN",
  "05",          "OPPLAND",           "0532",           "JEVNAKER",            "30",                "VIKEN",           "3053",          "JEVNAKER",
  "05",          "OPPLAND",           "0533",             "LUNNER",            "30",                "VIKEN",           "3054",            "LUNNER",
  "05",          "OPPLAND",           "0534",               "GRAN",            "34",            "INNLANDET",           "3446",              "GRAN",
  "05",          "OPPLAND",           "0536",        "SØNDRE LAND",            "34",            "INNLANDET",           "3447",       "SØNDRE LAND",
  "05",          "OPPLAND",           "0538",        "NORDRE LAND",            "34",            "INNLANDET",           "3448",       "NORDRE LAND",
  "05",          "OPPLAND",           "0540",         "SØR-AURDAL",            "34",            "INNLANDET",           "3449",        "SØR-AURDAL",
  "05",          "OPPLAND",           "0541",            "ETNEDAL",            "34",            "INNLANDET",           "3450",           "ETNEDAL",
  "05",          "OPPLAND",           "0542",        "NORD-AURDAL",            "34",            "INNLANDET",           "3451",       "NORD-AURDAL",
  "05",          "OPPLAND",           "0543",      "VESTRE SLIDRE",            "34",            "INNLANDET",           "3452",     "VESTRE SLIDRE",
  "05",          "OPPLAND",           "0544",      "ØYSTRE SLIDRE",            "34",            "INNLANDET",           "3453",     "ØYSTRE SLIDRE",
  "05",          "OPPLAND",           "0545",               "VANG",            "34",            "INNLANDET",           "3454",              "VANG",
  "06",         "BUSKERUD",           "0602",            "DRAMMEN",            "30",                "VIKEN",           "3005",           "DRAMMEN",
  "06",         "BUSKERUD",           "0604",          "KONGSBERG",            "30",                "VIKEN",           "3006",         "KONGSBERG",
  "06",         "BUSKERUD",           "0605",          "RINGERIKE",            "30",                "VIKEN",           "3007",         "RINGERIKE",
  "06",         "BUSKERUD",           "0612",               "HOLE",            "30",                "VIKEN",           "3038",              "HOLE",
  "06",         "BUSKERUD",           "0615",                "FLÅ",            "30",                "VIKEN",           "3039",               "FLÅ",
  "06",         "BUSKERUD",           "0616",        "NES (BUSK.)",            "30",                "VIKEN",           "3040",           "NESBYEN",
  "06",         "BUSKERUD",           "0617",                "GOL",            "30",                "VIKEN",           "3041",               "GOL",
  "06",         "BUSKERUD",           "0618",           "HEMSEDAL",            "30",                "VIKEN",           "3042",          "HEMSEDAL",
  "06",         "BUSKERUD",           "0619",                 "ÅL",            "30",                "VIKEN",           "3043",                "ÅL",
  "06",         "BUSKERUD",           "0620",                "HOL",            "30",                "VIKEN",           "3044",               "HOL",
  "06",         "BUSKERUD",           "0621",             "SIGDAL",            "30",                "VIKEN",           "3045",            "SIGDAL",
  "06",         "BUSKERUD",           "0622",         "KRØDSHERAD",            "30",                "VIKEN",           "3046",        "KRØDSHERAD",
  "06",         "BUSKERUD",           "0623",              "MODUM",            "30",                "VIKEN",           "3047",             "MODUM",
  "06",         "BUSKERUD",           "0624",         "ØVRE EIKER",            "30",                "VIKEN",           "3048",        "ØVRE EIKER",
  "06",         "BUSKERUD",           "0625",        "NEDRE EIKER",            "30",                "VIKEN",           "3005",           "DRAMMEN",
  "06",         "BUSKERUD",           "0626",               "LIER",            "30",                "VIKEN",           "3049",              "LIER",
  "06",         "BUSKERUD",           "0627",             "RØYKEN",            "30",                "VIKEN",           "3025",             "ASKER",
  "06",         "BUSKERUD",           "0628",              "HURUM",            "30",                "VIKEN",           "3025",             "ASKER",
  "06",         "BUSKERUD",           "0631",           "FLESBERG",            "30",                "VIKEN",           "3050",          "FLESBERG",
  "06",         "BUSKERUD",           "0632",             "ROLLAG",            "30",                "VIKEN",           "3051",            "ROLLAG",
  "06",         "BUSKERUD",           "0633",      "NORE OG UVDAL",            "30",                "VIKEN",           "3052",     "NORE OG UVDAL",
  "07",         "VESTFOLD",           "0701",             "HORTEN",            "38", "VESTFOLD OG TELEMARK",           "3801",            "HORTEN",
  "07",         "VESTFOLD",           "0704",           "TØNSBERG",            "38", "VESTFOLD OG TELEMARK",           "3803",          "TØNSBERG",
  "07",         "VESTFOLD",           "0710",         "SANDEFJORD",            "38", "VESTFOLD OG TELEMARK",           "3804",        "SANDEFJORD",
  "07",         "VESTFOLD",           "0711",            "SVELVIK",            "30",                "VIKEN",           "3005",           "DRAMMEN",
  "07",         "VESTFOLD",           "0712",             "LARVIK",            "38", "VESTFOLD OG TELEMARK",           "3805",            "LARVIK",
  "07",         "VESTFOLD",           "0713",     "SANDE (VESTF.)",            "38", "VESTFOLD OG TELEMARK",           "3802",       "HOLMESTRAND",
  "07",         "VESTFOLD",           "0715",        "HOLMESTRAND",            "38", "VESTFOLD OG TELEMARK",           "3802",       "HOLMESTRAND",
  "07",         "VESTFOLD",           "0716",                 "RE",            "38", "VESTFOLD OG TELEMARK",           "3803",          "TØNSBERG",
  "07",         "VESTFOLD",           "0729",             "FÆRDER",            "38", "VESTFOLD OG TELEMARK",           "3811",            "FÆRDER",
  "08",         "TELEMARK",           "0805",          "PORSGRUNN",            "38", "VESTFOLD OG TELEMARK",           "3806",         "PORSGRUNN",
  "08",         "TELEMARK",           "0806",              "SKIEN",            "38", "VESTFOLD OG TELEMARK",           "3807",             "SKIEN",
  "08",         "TELEMARK",           "0807",           "NOTODDEN",            "38", "VESTFOLD OG TELEMARK",           "3808",          "NOTODDEN",
  "08",         "TELEMARK",           "0811",             "SILJAN",            "38", "VESTFOLD OG TELEMARK",           "3812",            "SILJAN",
  "08",         "TELEMARK",           "0814",             "BAMBLE",            "38", "VESTFOLD OG TELEMARK",           "3813",            "BAMBLE",
  "08",         "TELEMARK",           "0815",            "KRAGERØ",            "38", "VESTFOLD OG TELEMARK",           "3814",           "KRAGERØ",
  "08",         "TELEMARK",           "0817",          "DRANGEDAL",            "38", "VESTFOLD OG TELEMARK",           "3815",         "DRANGEDAL",
  "08",         "TELEMARK",           "0819",               "NOME",            "38", "VESTFOLD OG TELEMARK",           "3816",              "NOME",
  "08",         "TELEMARK",           "0821",        "BØ (TELEM.)",            "38", "VESTFOLD OG TELEMARK",           "3817",     "MIDT-TELEMARK",
  "08",         "TELEMARK",           "0822",           "SAUHERAD",            "38", "VESTFOLD OG TELEMARK",           "3817",     "MIDT-TELEMARK",
  "08",         "TELEMARK",           "0826",               "TINN",            "38", "VESTFOLD OG TELEMARK",           "3818",              "TINN",
  "08",         "TELEMARK",           "0827",           "HJARTDAL",            "38", "VESTFOLD OG TELEMARK",           "3819",          "HJARTDAL",
  "08",         "TELEMARK",           "0828",            "SELJORD",            "38", "VESTFOLD OG TELEMARK",           "3820",           "SELJORD",
  "08",         "TELEMARK",           "0829",          "KVITESEID",            "38", "VESTFOLD OG TELEMARK",           "3821",         "KVITESEID",
  "08",         "TELEMARK",           "0830",           "NISSEDAL",            "38", "VESTFOLD OG TELEMARK",           "3822",          "NISSEDAL",
  "08",         "TELEMARK",           "0831",           "FYRESDAL",            "38", "VESTFOLD OG TELEMARK",           "3823",          "FYRESDAL",
  "08",         "TELEMARK",           "0833",              "TOKKE",            "38", "VESTFOLD OG TELEMARK",           "3824",             "TOKKE",
  "08",         "TELEMARK",           "0834",              "VINJE",            "38", "VESTFOLD OG TELEMARK",           "3825",             "VINJE",
  "09",       "AUST-AGDER",           "0901",              "RISØR",            "42",                "AGDER",           "4201",             "RISØR",
  "09",       "AUST-AGDER",           "0904",           "GRIMSTAD",            "42",                "AGDER",           "4202",          "GRIMSTAD",
  "09",       "AUST-AGDER",           "0906",            "ARENDAL",            "42",                "AGDER",           "4203",           "ARENDAL",
  "09",       "AUST-AGDER",           "0911",           "GJERSTAD",            "42",                "AGDER",           "4211",          "GJERSTAD",
  "09",       "AUST-AGDER",           "0912",          "VEGÅRSHEI",            "42",                "AGDER",           "4212",         "VEGÅRSHEI",
  "09",       "AUST-AGDER",           "0914",        "TVEDESTRAND",            "42",                "AGDER",           "4213",       "TVEDESTRAND",
  "09",       "AUST-AGDER",           "0919",            "FROLAND",            "42",                "AGDER",           "4214",           "FROLAND",
  "09",       "AUST-AGDER",           "0926",          "LILLESAND",            "42",                "AGDER",           "4215",         "LILLESAND",
  "09",       "AUST-AGDER",           "0928",           "BIRKENES",            "42",                "AGDER",           "4216",          "BIRKENES",
  "09",       "AUST-AGDER",           "0929",               "ÅMLI",            "42",                "AGDER",           "4217",              "ÅMLI",
  "09",       "AUST-AGDER",           "0935",            "IVELAND",            "42",                "AGDER",           "4218",           "IVELAND",
  "09",       "AUST-AGDER",           "0937",    "EVJE OG HORNNES",            "42",                "AGDER",           "4219",   "EVJE OG HORNNES",
  "09",       "AUST-AGDER",           "0938",            "BYGLAND",            "42",                "AGDER",           "4220",           "BYGLAND",
  "09",       "AUST-AGDER",           "0940",              "VALLE",            "42",                "AGDER",           "4221",             "VALLE",
  "09",       "AUST-AGDER",           "0941",              "BYKLE",            "42",                "AGDER",           "4222",             "BYKLE",
  "10",       "VEST-AGDER",           "1001",       "KRISTIANSAND",            "42",                "AGDER",           "4204",      "KRISTIANSAND",
  "10",       "VEST-AGDER",           "1002",             "MANDAL",            "42",                "AGDER",           "4205",         "LINDESNES",
  "10",       "VEST-AGDER",           "1003",            "FARSUND",            "42",                "AGDER",           "4206",           "FARSUND",
  "10",       "VEST-AGDER",           "1004",        "FLEKKEFJORD",            "42",                "AGDER",           "4207",       "FLEKKEFJORD",
  "10",       "VEST-AGDER",           "1014",           "VENNESLA",            "42",                "AGDER",           "4223",          "VENNESLA",
  "10",       "VEST-AGDER",           "1017",          "SONGDALEN",            "42",                "AGDER",           "4204",      "KRISTIANSAND",
  "10",       "VEST-AGDER",           "1018",              "SØGNE",            "42",                "AGDER",           "4204",      "KRISTIANSAND",
  "10",       "VEST-AGDER",           "1021",          "MARNARDAL",            "42",                "AGDER",           "4205",         "LINDESNES",
  "10",       "VEST-AGDER",           "1026",             "ÅSERAL",            "42",                "AGDER",           "4224",            "ÅSERAL",
  "10",       "VEST-AGDER",           "1027",           "AUDNEDAL",            "42",                "AGDER",           "4225",           "LYNGDAL",
  "10",       "VEST-AGDER",           "1029",          "LINDESNES",            "42",                "AGDER",           "4205",         "LINDESNES",
  "10",       "VEST-AGDER",           "1032",            "LYNGDAL",            "42",                "AGDER",           "4225",           "LYNGDAL",
  "10",       "VEST-AGDER",           "1034",         "HÆGEBOSTAD",            "42",                "AGDER",           "4226",        "HÆGEBOSTAD",
  "10",       "VEST-AGDER",           "1037",          "KVINESDAL",            "42",                "AGDER",           "4227",         "KVINESDAL",
  "10",       "VEST-AGDER",           "1046",             "SIRDAL",            "42",                "AGDER",           "4228",            "SIRDAL",
  "11",         "ROGALAND",           "1101",          "EIGERSUND",            "11",             "ROGALAND",           "1101",         "EIGERSUND",
  "11",         "ROGALAND",           "1102",            "SANDNES",            "11",             "ROGALAND",           "1108",           "SANDNES",
  "11",         "ROGALAND",           "1103",          "STAVANGER",            "11",             "ROGALAND",           "1103",         "STAVANGER",
  "11",         "ROGALAND",           "1106",          "HAUGESUND",            "11",             "ROGALAND",           "1106",         "HAUGESUND",
  "11",         "ROGALAND",           "1111",            "SOKNDAL",            "11",             "ROGALAND",           "1111",           "SOKNDAL",
  "11",         "ROGALAND",           "1112",               "LUND",            "11",             "ROGALAND",           "1112",              "LUND",
  "11",         "ROGALAND",           "1114",          "BJERKREIM",            "11",             "ROGALAND",           "1114",         "BJERKREIM",
  "11",         "ROGALAND",           "1119",                 "HÅ",            "11",             "ROGALAND",           "1119",                "HÅ",
  "11",         "ROGALAND",           "1120",              "KLEPP",            "11",             "ROGALAND",           "1120",             "KLEPP",
  "11",         "ROGALAND",           "1121",               "TIME",            "11",             "ROGALAND",           "1121",              "TIME",
  "11",         "ROGALAND",           "1122",            "GJESDAL",            "11",             "ROGALAND",           "1122",           "GJESDAL",
  "11",         "ROGALAND",           "1124",               "SOLA",            "11",             "ROGALAND",           "1124",              "SOLA",
  "11",         "ROGALAND",           "1127",          "RANDABERG",            "11",             "ROGALAND",           "1127",         "RANDABERG",
  "11",         "ROGALAND",           "1129",            "FORSAND",            "11",             "ROGALAND",           "1108",           "SANDNES",
  "11",         "ROGALAND",           "1130",             "STRAND",            "11",             "ROGALAND",           "1130",            "STRAND",
  "11",         "ROGALAND",           "1133",         "HJELMELAND",            "11",             "ROGALAND",           "1133",        "HJELMELAND",
  "11",         "ROGALAND",           "1134",             "SULDAL",            "11",             "ROGALAND",           "1134",            "SULDAL",
  "11",         "ROGALAND",           "1135",              "SAUDA",            "11",             "ROGALAND",           "1135",             "SAUDA",
  "11",         "ROGALAND",           "1141",             "FINNØY",            "11",             "ROGALAND",           "1103",         "STAVANGER",
  "11",         "ROGALAND",           "1142",           "RENNESØY",            "11",             "ROGALAND",           "1103",         "STAVANGER",
  "11",         "ROGALAND",           "1144",            "KVITSØY",            "11",             "ROGALAND",           "1144",           "KVITSØY",
  "11",         "ROGALAND",           "1145",               "BOKN",            "11",             "ROGALAND",           "1145",              "BOKN",
  "11",         "ROGALAND",           "1146",             "TYSVÆR",            "11",             "ROGALAND",           "1146",            "TYSVÆR",
  "11",         "ROGALAND",           "1149",             "KARMØY",            "11",             "ROGALAND",           "1149",            "KARMØY",
  "11",         "ROGALAND",           "1151",             "UTSIRA",            "11",             "ROGALAND",           "1151",            "UTSIRA",
  "11",         "ROGALAND",           "1160",         "VINDAFJORD",            "11",             "ROGALAND",           "1160",        "VINDAFJORD",
  "12",        "HORDALAND",           "1201",             "BERGEN",            "46",             "VESTLAND",           "4601",            "BERGEN",
  "12",        "HORDALAND",           "1211",               "ETNE",            "46",             "VESTLAND",           "4611",              "ETNE",
  "12",        "HORDALAND",           "1216",              "SVEIO",            "46",             "VESTLAND",           "4612",             "SVEIO",
  "12",        "HORDALAND",           "1219",              "BØMLO",            "46",             "VESTLAND",           "4613",             "BØMLO",
  "12",        "HORDALAND",           "1221",              "STORD",            "46",             "VESTLAND",           "4614",             "STORD",
  "12",        "HORDALAND",           "1222",             "FITJAR",            "46",             "VESTLAND",           "4615",            "FITJAR",
  "12",        "HORDALAND",           "1223",             "TYSNES",            "46",             "VESTLAND",           "4616",            "TYSNES",
  "12",        "HORDALAND",           "1224",         "KVINNHERAD",            "46",             "VESTLAND",           "4617",        "KVINNHERAD",
  "12",        "HORDALAND",           "1227",             "JONDAL",            "46",             "VESTLAND",           "4618",        "ULLENSVANG",
  "12",        "HORDALAND",           "1228",               "ODDA",            "46",             "VESTLAND",           "4618",        "ULLENSVANG",
  "12",        "HORDALAND",           "1231",         "ULLENSVANG",            "46",             "VESTLAND",           "4618",        "ULLENSVANG",
  "12",        "HORDALAND",           "1232",           "EIDFJORD",            "46",             "VESTLAND",           "4619",          "EIDFJORD",
  "12",        "HORDALAND",           "1233",              "ULVIK",            "46",             "VESTLAND",           "4620",             "ULVIK",
  "12",        "HORDALAND",           "1234",            "GRANVIN",            "46",             "VESTLAND",           "4621",              "VOSS",
  "12",        "HORDALAND",           "1235",               "VOSS",            "46",             "VESTLAND",           "4621",              "VOSS",
  "12",        "HORDALAND",           "1238",               "KVAM",            "46",             "VESTLAND",           "4622",              "KVAM",
  "12",        "HORDALAND",           "1241",               "FUSA",            "46",             "VESTLAND",           "4624",     "BJØRNAFJORDEN",
  "12",        "HORDALAND",           "1242",          "SAMNANGER",            "46",             "VESTLAND",           "4623",         "SAMNANGER",
  "12",        "HORDALAND",           "1243",     "OS (HORDALAND)",            "46",             "VESTLAND",           "4624",     "BJØRNAFJORDEN",
  "12",        "HORDALAND",           "1244",          "AUSTEVOLL",            "46",             "VESTLAND",           "4625",         "AUSTEVOLL",
  "12",        "HORDALAND",           "1245",               "SUND",            "46",             "VESTLAND",           "4626",          "ØYGARDEN",
  "12",        "HORDALAND",           "1246",              "FJELL",            "46",             "VESTLAND",           "4626",          "ØYGARDEN",
  "12",        "HORDALAND",           "1247",              "ASKØY",            "46",             "VESTLAND",           "4627",             "ASKØY",
  "12",        "HORDALAND",           "1251",            "VAKSDAL",            "46",             "VESTLAND",           "4628",           "VAKSDAL",
  "12",        "HORDALAND",           "1252",            "MODALEN",            "46",             "VESTLAND",           "4629",           "MODALEN",
  "12",        "HORDALAND",           "1253",            "OSTERØY",            "46",             "VESTLAND",           "4630",           "OSTERØY",
  "12",        "HORDALAND",           "1256",             "MELAND",            "46",             "VESTLAND",           "4631",             "ALVER",
  "12",        "HORDALAND",           "1259",           "ØYGARDEN",            "46",             "VESTLAND",           "4626",          "ØYGARDEN",
  "12",        "HORDALAND",           "1260",              "RADØY",            "46",             "VESTLAND",           "4631",             "ALVER",
  "12",        "HORDALAND",           "1263",             "LINDÅS",            "46",             "VESTLAND",           "4631",             "ALVER",
  "12",        "HORDALAND",           "1264",          "AUSTRHEIM",            "46",             "VESTLAND",           "4632",         "AUSTRHEIM",
  "12",        "HORDALAND",           "1265",              "FEDJE",            "46",             "VESTLAND",           "4633",             "FEDJE",
  "12",        "HORDALAND",           "1266",         "MASFJORDEN",            "46",             "VESTLAND",           "4634",        "MASFJORDEN",
  "14", "SOGN OG FJORDANE",           "1401",              "FLORA",            "46",             "VESTLAND",           "4602",              "KINN",
  "14", "SOGN OG FJORDANE",           "1411",              "GULEN",            "46",             "VESTLAND",           "4635",             "GULEN",
  "14", "SOGN OG FJORDANE",           "1412",             "SOLUND",            "46",             "VESTLAND",           "4636",            "SOLUND",
  "14", "SOGN OG FJORDANE",           "1413",          "HYLLESTAD",            "46",             "VESTLAND",           "4637",         "HYLLESTAD",
  "14", "SOGN OG FJORDANE",           "1416",           "HØYANGER",            "46",             "VESTLAND",           "4638",          "HØYANGER",
  "14", "SOGN OG FJORDANE",           "1417",                "VIK",            "46",             "VESTLAND",           "4639",               "VIK",
  "14", "SOGN OG FJORDANE",           "1418",         "BALESTRAND",            "46",             "VESTLAND",           "4640",           "SOGNDAL",
  "14", "SOGN OG FJORDANE",           "1419",          "LEIKANGER",            "46",             "VESTLAND",           "4640",           "SOGNDAL",
  "14", "SOGN OG FJORDANE",           "1420",            "SOGNDAL",            "46",             "VESTLAND",           "4640",           "SOGNDAL",
  "14", "SOGN OG FJORDANE",           "1421",            "AURLAND",            "46",             "VESTLAND",           "4641",           "AURLAND",
  "14", "SOGN OG FJORDANE",           "1422",             "LÆRDAL",            "46",             "VESTLAND",           "4642",            "LÆRDAL",
  "14", "SOGN OG FJORDANE",           "1424",              "ÅRDAL",            "46",             "VESTLAND",           "4643",             "ÅRDAL",
  "14", "SOGN OG FJORDANE",           "1426",             "LUSTER",            "46",             "VESTLAND",           "4644",            "LUSTER",
  "14", "SOGN OG FJORDANE",           "1428",            "ASKVOLL",            "46",             "VESTLAND",           "4645",           "ASKVOLL",
  "14", "SOGN OG FJORDANE",           "1429",             "FJALER",            "46",             "VESTLAND",           "4646",            "FJALER",
  "14", "SOGN OG FJORDANE",           "1430",             "GAULAR",            "46",             "VESTLAND",           "4647",         "SUNNFJORD",
  "14", "SOGN OG FJORDANE",           "1431",            "JØLSTER",            "46",             "VESTLAND",           "4647",         "SUNNFJORD",
  "14", "SOGN OG FJORDANE",           "1432",              "FØRDE",            "46",             "VESTLAND",           "4647",         "SUNNFJORD",
  "14", "SOGN OG FJORDANE",           "1433",           "NAUSTDAL",            "46",             "VESTLAND",           "4647",         "SUNNFJORD",
  "14", "SOGN OG FJORDANE",           "1438",          "BREMANGER",            "46",             "VESTLAND",           "4648",         "BREMANGER",
  "14", "SOGN OG FJORDANE",           "1439",             "VÅGSØY",            "46",             "VESTLAND",           "4602",              "KINN",
  "14", "SOGN OG FJORDANE",           "1441",              "SELJE",            "46",             "VESTLAND",           "4649",              "STAD",
  "14", "SOGN OG FJORDANE",           "1443",                "EID",            "46",             "VESTLAND",           "4649",              "STAD",
  "14", "SOGN OG FJORDANE",           "1444",          "HORNINDAL",            "15",      "MØRE OG ROMSDAL",           "1577",             "VOLDA",
  "14", "SOGN OG FJORDANE",           "1445",            "GLOPPEN",            "46",             "VESTLAND",           "4650",           "GLOPPEN",
  "14", "SOGN OG FJORDANE",           "1449",              "STRYN",            "46",             "VESTLAND",           "4651",             "STRYN",
  "15",  "MØRE OG ROMSDAL",           "1502",              "MOLDE",            "15",      "MØRE OG ROMSDAL",           "1506",             "MOLDE",
  "15",  "MØRE OG ROMSDAL",           "1504",            "ÅLESUND",            "15",      "MØRE OG ROMSDAL",           "1507",           "ÅLESUND",
  "15",  "MØRE OG ROMSDAL",           "1505",       "KRISTIANSUND",            "15",      "MØRE OG ROMSDAL",           "1505",      "KRISTIANSUND",
  "15",  "MØRE OG ROMSDAL",           "1511",           "VANYLVEN",            "15",      "MØRE OG ROMSDAL",           "1511",          "VANYLVEN",
  "15",  "MØRE OG ROMSDAL",           "1514",              "SANDE",            "15",      "MØRE OG ROMSDAL",           "1514",             "SANDE",
  "15",  "MØRE OG ROMSDAL",           "1515",   "HERØY (M. OG R.)",            "15",      "MØRE OG ROMSDAL",           "1515",  "HERØY (M. OG R.)",
  "15",  "MØRE OG ROMSDAL",           "1516",            "ULSTEIN",            "15",      "MØRE OG ROMSDAL",           "1516",           "ULSTEIN",
  "15",  "MØRE OG ROMSDAL",           "1517",             "HAREID",            "15",      "MØRE OG ROMSDAL",           "1517",            "HAREID",
  "15",  "MØRE OG ROMSDAL",           "1519",              "VOLDA",            "15",      "MØRE OG ROMSDAL",           "1577",             "VOLDA",
  "15",  "MØRE OG ROMSDAL",           "1520",              "ØRSTA",            "15",      "MØRE OG ROMSDAL",           "1520",             "ØRSTA",
  "15",  "MØRE OG ROMSDAL",           "1523",             "ØRSKOG",            "15",      "MØRE OG ROMSDAL",           "1507",           "ÅLESUND",
  "15",  "MØRE OG ROMSDAL",           "1524",            "NORDDAL",            "15",      "MØRE OG ROMSDAL",           "1578",             "FJORD",
  "15",  "MØRE OG ROMSDAL",           "1525",            "STRANDA",            "15",      "MØRE OG ROMSDAL",           "1525",           "STRANDA",
  "15",  "MØRE OG ROMSDAL",           "1526",            "STORDAL",            "15",      "MØRE OG ROMSDAL",           "1578",             "FJORD",
  "15",  "MØRE OG ROMSDAL",           "1528",          "SYKKYLVEN",            "15",      "MØRE OG ROMSDAL",           "1528",         "SYKKYLVEN",
  "15",  "MØRE OG ROMSDAL",           "1529",             "SKODJE",            "15",      "MØRE OG ROMSDAL",           "1507",           "ÅLESUND",
  "15",  "MØRE OG ROMSDAL",           "1531",               "SULA",            "15",      "MØRE OG ROMSDAL",           "1531",              "SULA",
  "15",  "MØRE OG ROMSDAL",           "1532",              "GISKE",            "15",      "MØRE OG ROMSDAL",           "1532",             "GISKE",
  "15",  "MØRE OG ROMSDAL",           "1534",              "HARAM",            "15",      "MØRE OG ROMSDAL",           "1507",           "ÅLESUND",
  "15",  "MØRE OG ROMSDAL",           "1535",            "VESTNES",            "15",      "MØRE OG ROMSDAL",           "1535",           "VESTNES",
  "15",  "MØRE OG ROMSDAL",           "1539",              "RAUMA",            "15",      "MØRE OG ROMSDAL",           "1539",             "RAUMA",
  "15",  "MØRE OG ROMSDAL",           "1543",             "NESSET",            "15",      "MØRE OG ROMSDAL",           "1506",             "MOLDE",
  "15",  "MØRE OG ROMSDAL",           "1545",            "MIDSUND",            "15",      "MØRE OG ROMSDAL",           "1506",             "MOLDE",
  "15",  "MØRE OG ROMSDAL",           "1546",             "SANDØY",            "15",      "MØRE OG ROMSDAL",           "1507",           "ÅLESUND",
  "15",  "MØRE OG ROMSDAL",           "1547",              "AUKRA",            "15",      "MØRE OG ROMSDAL",           "1547",             "AUKRA",
  "15",  "MØRE OG ROMSDAL",           "1548",              "FRÆNA",            "15",      "MØRE OG ROMSDAL",           "1579",        "HUSTADVIKA",
  "15",  "MØRE OG ROMSDAL",           "1551",               "EIDE",            "15",      "MØRE OG ROMSDAL",           "1579",        "HUSTADVIKA",
  "15",  "MØRE OG ROMSDAL",           "1554",             "AVERØY",            "15",      "MØRE OG ROMSDAL",           "1554",            "AVERØY",
  "15",  "MØRE OG ROMSDAL",           "1557",            "GJEMNES",            "15",      "MØRE OG ROMSDAL",           "1557",           "GJEMNES",
  "15",  "MØRE OG ROMSDAL",           "1560",           "TINGVOLL",            "15",      "MØRE OG ROMSDAL",           "1560",          "TINGVOLL",
  "15",  "MØRE OG ROMSDAL",           "1563",            "SUNNDAL",            "15",      "MØRE OG ROMSDAL",           "1563",           "SUNNDAL",
  "15",  "MØRE OG ROMSDAL",           "1566",           "SURNADAL",            "15",      "MØRE OG ROMSDAL",           "1566",          "SURNADAL",
  "15",  "MØRE OG ROMSDAL",           "1571",              "HALSA",            "50",            "TRØNDELAG",           "5055",              "HEIM",
  "15",  "MØRE OG ROMSDAL",           "1573",              "SMØLA",            "15",      "MØRE OG ROMSDAL",           "1573",             "SMØLA",
  "15",  "MØRE OG ROMSDAL",           "1576",               "AURE",            "15",      "MØRE OG ROMSDAL",           "1576",              "AURE",
  "18",         "NORDLAND",           "1804",               "BODØ",            "18",             "NORDLAND",           "1804",              "BODØ",
  "18",         "NORDLAND",           "1805",             "NARVIK",            "18",             "NORDLAND",           "1806",            "NARVIK",
  "18",         "NORDLAND",           "1811",             "BINDAL",            "18",             "NORDLAND",           "1811",            "BINDAL",
  "18",         "NORDLAND",           "1812",              "SØMNA",            "18",             "NORDLAND",           "1812",             "SØMNA",
  "18",         "NORDLAND",           "1813",            "BRØNNØY",            "18",             "NORDLAND",           "1813",           "BRØNNØY",
  "18",         "NORDLAND",           "1815",               "VEGA",            "18",             "NORDLAND",           "1815",              "VEGA",
  "18",         "NORDLAND",           "1816",          "VEVELSTAD",            "18",             "NORDLAND",           "1816",         "VEVELSTAD",
  "18",         "NORDLAND",           "1818",     "HERØY (NORDL.)",            "18",             "NORDLAND",           "1818",    "HERØY (NORDL.)",
  "18",         "NORDLAND",           "1820",          "ALSTAHAUG",            "18",             "NORDLAND",           "1820",         "ALSTAHAUG",
  "18",         "NORDLAND",           "1822",          "LEIRFJORD",            "18",             "NORDLAND",           "1822",         "LEIRFJORD",
  "18",         "NORDLAND",           "1824",              "VEFSN",            "18",             "NORDLAND",           "1824",             "VEFSN",
  "18",         "NORDLAND",           "1825",              "GRANE",            "18",             "NORDLAND",           "1825",             "GRANE",
  "18",         "NORDLAND",           "1826",       "HATTFJELLDAL",            "18",             "NORDLAND",           "1826",      "HATTFJELLDAL",
  "18",         "NORDLAND",           "1827",              "DØNNA",            "18",             "NORDLAND",           "1827",             "DØNNA",
  "18",         "NORDLAND",           "1828",              "NESNA",            "18",             "NORDLAND",           "1828",             "NESNA",
  "18",         "NORDLAND",           "1832",             "HEMNES",            "18",             "NORDLAND",           "1832",            "HEMNES",
  "18",         "NORDLAND",           "1833",               "RANA",            "18",             "NORDLAND",           "1833",              "RANA",
  "18",         "NORDLAND",           "1834",              "LURØY",            "18",             "NORDLAND",           "1834",             "LURØY",
  "18",         "NORDLAND",           "1835",              "TRÆNA",            "18",             "NORDLAND",           "1835",             "TRÆNA",
  "18",         "NORDLAND",           "1836",              "RØDØY",            "18",             "NORDLAND",           "1836",             "RØDØY",
  "18",         "NORDLAND",           "1837",              "MELØY",            "18",             "NORDLAND",           "1837",             "MELØY",
  "18",         "NORDLAND",           "1838",          "GILDESKÅL",            "18",             "NORDLAND",           "1838",         "GILDESKÅL",
  "18",         "NORDLAND",           "1839",             "BEIARN",            "18",             "NORDLAND",           "1839",            "BEIARN",
  "18",         "NORDLAND",           "1840",            "SALTDAL",            "18",             "NORDLAND",           "1840",           "SALTDAL",
  "18",         "NORDLAND",           "1841",             "FAUSKE",            "18",             "NORDLAND",           "1841",            "FAUSKE",
  "18",         "NORDLAND",           "1845",            "SØRFOLD",            "18",             "NORDLAND",           "1845",           "SØRFOLD",
  "18",         "NORDLAND",           "1848",            "STEIGEN",            "18",             "NORDLAND",           "1848",           "STEIGEN",
  "18",         "NORDLAND",           "1849",            "HAMARØY",            "18",             "NORDLAND",           "1875",           "HAMARØY",
  "18",         "NORDLAND",           "1850",   "TYSFJORD (DELES)",            "18",             "NORDLAND",           "1806",            "NARVIK",
  "18",         "NORDLAND",           "1850",   "TYSFJORD (DELES)",            "18",             "NORDLAND",           "1875",           "HAMARØY",
  "18",         "NORDLAND",           "1851",           "LØDINGEN",            "18",             "NORDLAND",           "1851",          "LØDINGEN",
  "18",         "NORDLAND",           "1852",          "TJELDSUND",            "54",    "TROMS OG FINNMARK",           "5412",         "TJELDSUND",
  "18",         "NORDLAND",           "1853",             "EVENES",            "18",             "NORDLAND",           "1853",            "EVENES",
  "18",         "NORDLAND",           "1854",          "BALLANGEN",            "18",             "NORDLAND",           "1806",            "NARVIK",
  "18",         "NORDLAND",           "1856",               "RØST",            "18",             "NORDLAND",           "1856",              "RØST",
  "18",         "NORDLAND",           "1857",              "VÆRØY",            "18",             "NORDLAND",           "1857",             "VÆRØY",
  "18",         "NORDLAND",           "1859",           "FLAKSTAD",            "18",             "NORDLAND",           "1859",          "FLAKSTAD",
  "18",         "NORDLAND",           "1860",          "VESTVÅGØY",            "18",             "NORDLAND",           "1860",         "VESTVÅGØY",
  "18",         "NORDLAND",           "1865",              "VÅGAN",            "18",             "NORDLAND",           "1865",             "VÅGAN",
  "18",         "NORDLAND",           "1866",             "HADSEL",            "18",             "NORDLAND",           "1866",            "HADSEL",
  "18",         "NORDLAND",           "1867",                 "BØ",            "18",             "NORDLAND",           "1867",                "BØ",
  "18",         "NORDLAND",           "1868",             "ØKSNES",            "18",             "NORDLAND",           "1868",            "ØKSNES",
  "18",         "NORDLAND",           "1870",           "SORTLAND",            "18",             "NORDLAND",           "1870",          "SORTLAND",
  "18",         "NORDLAND",           "1871",              "ANDØY",            "18",             "NORDLAND",           "1871",             "ANDØY",
  "18",         "NORDLAND",           "1874",           "MOSKENES",            "18",             "NORDLAND",           "1874",          "MOSKENES",
  "19",            "TROMS",           "1902",             "TROMSØ",            "54",    "TROMS OG FINNMARK",           "5401",            "TROMSØ",
  "19",            "TROMS",           "1903",            "HARSTAD",            "54",    "TROMS OG FINNMARK",           "5402",           "HARSTAD",
  "19",            "TROMS",           "1911",           "KVÆFJORD",            "54",    "TROMS OG FINNMARK",           "5411",          "KVÆFJORD",
  "19",            "TROMS",           "1913",           "SKÅNLAND",            "54",    "TROMS OG FINNMARK",           "5412",         "TJELDSUND",
  "19",            "TROMS",           "1917",            "IBESTAD",            "54",    "TROMS OG FINNMARK",           "5413",           "IBESTAD",
  "19",            "TROMS",           "1919",          "GRATANGEN",            "54",    "TROMS OG FINNMARK",           "5414",         "GRATANGEN",
  "19",            "TROMS",           "1920",           "LAVANGEN",            "54",    "TROMS OG FINNMARK",           "5415",          "LAVANGEN",
  "19",            "TROMS",           "1922",              "BARDU",            "54",    "TROMS OG FINNMARK",           "5416",             "BARDU",
  "19",            "TROMS",           "1923",           "SALANGEN",            "54",    "TROMS OG FINNMARK",           "5417",          "SALANGEN",
  "19",            "TROMS",           "1924",            "MÅLSELV",            "54",    "TROMS OG FINNMARK",           "5418",           "MÅLSELV",
  "19",            "TROMS",           "1925",           "SØRREISA",            "54",    "TROMS OG FINNMARK",           "5419",          "SØRREISA",
  "19",            "TROMS",           "1926",              "DYRØY",            "54",    "TROMS OG FINNMARK",           "5420",             "DYRØY",
  "19",            "TROMS",           "1927",             "TRANØY",            "54",    "TROMS OG FINNMARK",           "5421",             "SENJA",
  "19",            "TROMS",           "1928",            "TORSKEN",            "54",    "TROMS OG FINNMARK",           "5421",             "SENJA",
  "19",            "TROMS",           "1929",               "BERG",            "54",    "TROMS OG FINNMARK",           "5421",             "SENJA",
  "19",            "TROMS",           "1931",             "LENVIK",            "54",    "TROMS OG FINNMARK",           "5421",             "SENJA",
  "19",            "TROMS",           "1933",          "BALSFJORD",            "54",    "TROMS OG FINNMARK",           "5422",         "BALSFJORD",
  "19",            "TROMS",           "1936",            "KARLSØY",            "54",    "TROMS OG FINNMARK",           "5423",           "KARLSØY",
  "19",            "TROMS",           "1938",             "LYNGEN",            "54",    "TROMS OG FINNMARK",           "5424",            "LYNGEN",
  "19",            "TROMS",           "1939",          "STORFJORD",            "54",    "TROMS OG FINNMARK",           "5425",         "STORFJORD",
  "19",            "TROMS",           "1940",            "KÅFJORD",            "54",    "TROMS OG FINNMARK",           "5426",           "KÅFJORD",
  "19",            "TROMS",           "1941",           "SKJERVØY",            "54",    "TROMS OG FINNMARK",           "5427",          "SKJERVØY",
  "19",            "TROMS",           "1942",          "NORDREISA",            "54",    "TROMS OG FINNMARK",           "5428",         "NORDREISA",
  "19",            "TROMS",           "1943",          "KVÆNANGEN",            "54",    "TROMS OG FINNMARK",           "5429",         "KVÆNANGEN",
  "20",         "FINNMARK",           "2002",              "VARDØ",            "54",    "TROMS OG FINNMARK",           "5404",             "VARDØ",
  "20",         "FINNMARK",           "2003",              "VADSØ",            "54",    "TROMS OG FINNMARK",           "5405",             "VADSØ",
  "20",         "FINNMARK",           "2004",         "HAMMERFEST",            "54",    "TROMS OG FINNMARK",           "5406",        "HAMMERFEST",
  "20",         "FINNMARK",           "2011",         "KAUTOKEINO",            "54",    "TROMS OG FINNMARK",           "5430",        "KAUTOKEINO",
  "20",         "FINNMARK",           "2012",               "ALTA",            "54",    "TROMS OG FINNMARK",           "5403",              "ALTA",
  "20",         "FINNMARK",           "2014",              "LOPPA",            "54",    "TROMS OG FINNMARK",           "5432",             "LOPPA",
  "20",         "FINNMARK",           "2015",             "HASVIK",            "54",    "TROMS OG FINNMARK",           "5433",            "HASVIK",
  "20",         "FINNMARK",           "2017",           "KVALSUND",            "54",    "TROMS OG FINNMARK",           "5406",        "HAMMERFEST",
  "20",         "FINNMARK",           "2018",              "MÅSØY",            "54",    "TROMS OG FINNMARK",           "5434",             "MÅSØY",
  "20",         "FINNMARK",           "2019",           "NORDKAPP",            "54",    "TROMS OG FINNMARK",           "5435",          "NORDKAPP",
  "20",         "FINNMARK",           "2020",          "PORSANGER",            "54",    "TROMS OG FINNMARK",           "5436",         "PORSANGER",
  "20",         "FINNMARK",           "2021",           "KARASJOK",            "54",    "TROMS OG FINNMARK",           "5437",          "KARASJOK",
  "20",         "FINNMARK",           "2022",            "LEBESBY",            "54",    "TROMS OG FINNMARK",           "5438",           "LEBESBY",
  "20",         "FINNMARK",           "2023",             "GAMVIK",            "54",    "TROMS OG FINNMARK",           "5439",            "GAMVIK",
  "20",         "FINNMARK",           "2024",           "BERLEVÅG",            "54",    "TROMS OG FINNMARK",           "5440",          "BERLEVÅG",
  "20",         "FINNMARK",           "2025",               "TANA",            "54",    "TROMS OG FINNMARK",           "5441",              "TANA",
  "20",         "FINNMARK",           "2027",            "NESSEBY",            "54",    "TROMS OG FINNMARK",           "5442",           "NESSEBY",
  "20",         "FINNMARK",           "2028",          "BÅTSFJORD",            "54",    "TROMS OG FINNMARK",           "5443",         "BÅTSFJORD",
  "20",         "FINNMARK",           "2030",       "SØR-VARANGER",            "54",    "TROMS OG FINNMARK",           "5444",      "SØR-VARANGER",
  "50",        "TRØNDELAG",           "5001",          "TRONDHEIM",            "50",            "TRØNDELAG",           "5001",         "TRONDHEIM",
  "50",        "TRØNDELAG",           "5004",          "STEINKJER",            "50",            "TRØNDELAG",           "5006",         "STEINKJER",
  "50",        "TRØNDELAG",           "5005",             "NAMSOS",            "50",            "TRØNDELAG",           "5007",            "NAMSOS",
  "50",        "TRØNDELAG",           "5011",              "HEMNE",            "50",            "TRØNDELAG",           "5055",              "HEIM",
  "50",        "TRØNDELAG",           "5012", "SNILLFJORD (DELES)",            "50",            "TRØNDELAG",           "5055",              "HEIM",
  "50",        "TRØNDELAG",           "5012", "SNILLFJORD (DELES)",            "50",            "TRØNDELAG",           "5056",             "HITRA",
  "50",        "TRØNDELAG",           "5012", "SNILLFJORD (DELES)",            "50",            "TRØNDELAG",           "5059",           "ORKLAND",
  "50",        "TRØNDELAG",           "5013",              "HITRA",            "50",            "TRØNDELAG",           "5056",             "HITRA",
  "50",        "TRØNDELAG",           "5014",              "FRØYA",            "50",            "TRØNDELAG",           "5014",             "FRØYA",
  "50",        "TRØNDELAG",           "5015",             "ØRLAND",            "50",            "TRØNDELAG",           "5057",            "ØRLAND",
  "50",        "TRØNDELAG",           "5016",            "AGDENES",            "50",            "TRØNDELAG",           "5059",           "ORKLAND",
  "50",        "TRØNDELAG",           "5017",              "BJUGN",            "50",            "TRØNDELAG",           "5057",            "ØRLAND",
  "50",        "TRØNDELAG",           "5018",             "ÅFJORD",            "50",            "TRØNDELAG",           "5058",            "ÅFJORD",
  "50",        "TRØNDELAG",           "5019",               "ROAN",            "50",            "TRØNDELAG",           "5058",            "ÅFJORD",
  "50",        "TRØNDELAG",           "5020",               "OSEN",            "50",            "TRØNDELAG",           "5020",              "OSEN",
  "50",        "TRØNDELAG",           "5021",             "OPPDAL",            "50",            "TRØNDELAG",           "5021",            "OPPDAL",
  "50",        "TRØNDELAG",           "5022",            "RENNEBU",            "50",            "TRØNDELAG",           "5022",           "RENNEBU",
  "50",        "TRØNDELAG",           "5023",             "MELDAL",            "50",            "TRØNDELAG",           "5059",           "ORKLAND",
  "50",        "TRØNDELAG",           "5024",             "ORKDAL",            "50",            "TRØNDELAG",           "5059",           "ORKLAND",
  "50",        "TRØNDELAG",           "5025",              "RØROS",            "50",            "TRØNDELAG",           "5025",             "RØROS",
  "50",        "TRØNDELAG",           "5026",           "HOLTÅLEN",            "50",            "TRØNDELAG",           "5026",          "HOLTÅLEN",
  "50",        "TRØNDELAG",           "5027",     "MIDTRE GAULDAL",            "50",            "TRØNDELAG",           "5027",    "MIDTRE GAULDAL",
  "50",        "TRØNDELAG",           "5028",             "MELHUS",            "50",            "TRØNDELAG",           "5028",            "MELHUS",
  "50",        "TRØNDELAG",           "5029",              "SKAUN",            "50",            "TRØNDELAG",           "5029",             "SKAUN",
  "50",        "TRØNDELAG",           "5030",              "KLÆBU",            "50",            "TRØNDELAG",           "5001",         "TRONDHEIM",
  "50",        "TRØNDELAG",           "5031",             "MALVIK",            "50",            "TRØNDELAG",           "5031",            "MALVIK",
  "50",        "TRØNDELAG",           "5032",              "SELBU",            "50",            "TRØNDELAG",           "5032",             "SELBU",
  "50",        "TRØNDELAG",           "5033",              "TYDAL",            "50",            "TRØNDELAG",           "5033",             "TYDAL",
  "50",        "TRØNDELAG",           "5034",            "MERÅKER",            "50",            "TRØNDELAG",           "5034",           "MERÅKER",
  "50",        "TRØNDELAG",           "5035",           "STJØRDAL",            "50",            "TRØNDELAG",           "5035",          "STJØRDAL",
  "50",        "TRØNDELAG",           "5036",             "FROSTA",            "50",            "TRØNDELAG",           "5036",            "FROSTA",
  "50",        "TRØNDELAG",           "5037",           "LEVANGER",            "50",            "TRØNDELAG",           "5037",          "LEVANGER",
  "50",        "TRØNDELAG",           "5038",             "VERDAL",            "50",            "TRØNDELAG",           "5038",            "VERDAL",
  "50",        "TRØNDELAG",           "5039",             "VERRAN",            "50",            "TRØNDELAG",           "5006",         "STEINKJER",
  "50",        "TRØNDELAG",           "5040",         "NAMDALSEID",            "50",            "TRØNDELAG",           "5007",            "NAMSOS",
  "50",        "TRØNDELAG",           "5041",              "SNÅSA",            "50",            "TRØNDELAG",           "5041",             "SNÅSA",
  "50",        "TRØNDELAG",           "5042",             "LIERNE",            "50",            "TRØNDELAG",           "5042",            "LIERNE",
  "50",        "TRØNDELAG",           "5043",            "RØYRVIK",            "50",            "TRØNDELAG",           "5043",           "RØYRVIK",
  "50",        "TRØNDELAG",           "5044",         "NAMSSKOGAN",            "50",            "TRØNDELAG",           "5044",        "NAMSSKOGAN",
  "50",        "TRØNDELAG",           "5045",              "GRONG",            "50",            "TRØNDELAG",           "5045",             "GRONG",
  "50",        "TRØNDELAG",           "5046",          "HØYLANDET",            "50",            "TRØNDELAG",           "5046",         "HØYLANDET",
  "50",        "TRØNDELAG",           "5047",          "OVERHALLA",            "50",            "TRØNDELAG",           "5047",         "OVERHALLA",
  "50",        "TRØNDELAG",           "5048",             "FOSNES",            "50",            "TRØNDELAG",           "5007",            "NAMSOS",
  "50",        "TRØNDELAG",           "5049",          "FLATANGER",            "50",            "TRØNDELAG",           "5049",         "FLATANGER",
  "50",        "TRØNDELAG",           "5050",              "VIKNA",            "50",            "TRØNDELAG",           "5060",         "NÆRØYSUND",
  "50",        "TRØNDELAG",           "5051",              "NÆRØY",            "50",            "TRØNDELAG",           "5060",         "NÆRØYSUND",
  "50",        "TRØNDELAG",           "5052",               "LEKA",            "50",            "TRØNDELAG",           "5052",              "LEKA",
  "50",        "TRØNDELAG",           "5053",            "INDERØY",            "50",            "TRØNDELAG",           "5053",           "INDERØY",
  "50",        "TRØNDELAG",           "5054",        "INDRE FOSEN",            "50",            "TRØNDELAG",           "5054",       "INDRE FOSEN",
  "50",        "TRØNDELAG",           "5061",             "RINDAL",            "50",            "TRØNDELAG",           "5061",            "RINDAL"
)

#new "kommuner" is in column Kommunenavn.2020. Must sort on unigue to get a list of only the 356 new "kommuner". And remove column Kommunenavn..2019:
library(dplyr)
kommuner_fylker2020_unique <- kommuner_fylker2020_raw %>% distinct(Kommunenr..2020, .keep_all = TRUE) %>%
  select(Fylkesnr..2020, Fylkesnavn.2020, Kommunenr..2020, Kommunenavn.2020)

#join the tibble with "kommunenavn" spelled with small letters (the first table loaded above):
kommuner_fylker2020 <- kommuner_fylker2020_unique %>% full_join(kommuner2020, by=c("Kommunenr..2020"="Nummer"))

##if you instead of all including the data generation above in this .R-file, want to write the data to package and then read them, do this:
##write.csv2(kommuner_fylker2020, file = "LOCALPATH.../norspis2/inst/extdata/kommuner_fylker2020", fileEncoding = "UTF-8")
#write.csv2(kommuner_fylker2020, file = "LOCALPATH.../norspis2/inst/extdata/kommuner_fylker2020", fileEncoding = "UTF-8")
# #read kommune and fylke data (these data are made in the script kommuner_DATA_script.R in  RNOTES)
# # kommuner_fylker2020 <- read.csv2(file = "LOCALPATH.../norspis2/inst/extdata/kommuner_fylker2020", fileEncoding = "UTF-8")
# kommuner_fylker2020 <- read.csv2(file = "LOCALPATH.../norspis2/inst/extdata/kommuner_fylker2020", fileEncoding = "UTF-8")


#make string with "kommuner" for each "fylke":
TromsFinnmark <- kommuner_fylker2020[kommuner_fylker2020$Fylkesnavn.2020 =='TROMS OG FINNMARK',]$Kommunenavn
Nordland <- kommuner_fylker2020[kommuner_fylker2020$Fylkesnavn.2020 =='NORDLAND',]$Kommunenavn
Trondelag <- kommuner_fylker2020[kommuner_fylker2020$Fylkesnavn.2020 =='TRØNDELAG',]$Kommunenavn
MoreRomsdal <- kommuner_fylker2020[kommuner_fylker2020$Fylkesnavn.2020 =='MØRE OG ROMSDAL',]$Kommunenavn
Vestland <- kommuner_fylker2020[kommuner_fylker2020$Fylkesnavn.2020 =='VESTLAND',]$Kommunenavn
Rogaland <- kommuner_fylker2020[kommuner_fylker2020$Fylkesnavn.2020 =='ROGALAND',]$Kommunenavn
Agder <- kommuner_fylker2020[kommuner_fylker2020$Fylkesnavn.2020 =='AGDER',]$Kommunenavn
VestfoldTelemark <- kommuner_fylker2020[kommuner_fylker2020$Fylkesnavn.2020 =='VESTFOLD OG TELEMARK',]$Kommunenavn
Viken <- kommuner_fylker2020[kommuner_fylker2020$Fylkesnavn.2020 =='VIKEN',]$Kommunenavn
Oslo <- kommuner_fylker2020[kommuner_fylker2020$Fylkesnavn.2020 =='OSLO',]$Kommunenavn
Innlandet <- kommuner_fylker2020[kommuner_fylker2020$Fylkesnavn.2020 =='INNLANDET',]$Kommunenavn


TromsFinnmark_collapsed <- paste(TromsFinnmark, collapse=";")
Nordland_collapsed <- paste(Nordland, collapse=";")
Trondelag_collapsed <- paste(Trondelag, collapse=";")
MoreRomsdal_collapsed <- paste(MoreRomsdal, collapse=";")
Vestland_collapsed <- paste(Vestland, collapse=";")
Rogaland_collapsed <- paste(Rogaland, collapse=";")
Agder_collapsed <- paste(Agder, collapse=";")
VestfoldTelemark_collapsed <- paste(VestfoldTelemark, collapse=";")
Viken_collapsed <- paste(Viken, collapse=";")
Oslo_collapsed <- paste(Oslo, collapse=";")
Innlandet_collapsed <- paste(Innlandet, collapse=";")
