---
title: "Rapport - NorSpis"
author: 'Nasjonal oversikt til fagrådsmøte 2021'
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: 2
  html_document:
    df_print: paged
params: 
  reshID: 700821
  dateFrom: !r format(Sys.Date(), "%Y")
  dateTo: "`r Sys.Date()`" 
---

[//]: # Just a list of usefull rmarkdown formatting commands:
[//]: # \pagebreak


[//]: # just setting things up
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  echo = params$reshID,
  warning=FALSE,
  comment = "#>",
  cache.path = 'F:/'
)
```

```{r loadPackages, include=FALSE}
#rm(list=ls()) WARNING: Do not use this line in parameterized .Rmd-documents, or else the parameters will not be found 
library(rapbase)
library(tidyverse)
library(norspis2)
```

[//]: # remember to load data - use "script-to-load-data-locally-norspis (...)"

```{r}
library(dplyr)
#------DATA norspis2
RegData2 <- norspis2::fun1_1_import_data_FEA(path_data="F:/2021-04-12_data-til-aarsresultater/", #disk and folder of data to import
                                             date_data="2021-04-12")

RegDataBeh2 <- norspis2::fun1_2_import_data_B(path_data="F:/2021-04-12_data-til-aarsresultater/", #disk and folder of data to import
                                              date_data="2021-04-12")
#Five datasets (outputted in a list):
DL <- norspis2::fun2_dataList(myInData1 = RegData2, myInData2 = RegDataBeh2)
#---DATA norspis2 (END)
#-----DATA  for norspis functions
#When we use norspis functions we use the call "RegData" (while we in norspis2 use DL$RegData12345)
RegData <- RegData2
#---DATA norspis2 (END)
```


[//]: # paramemters 

<!-- ```{r} -->
<!-- reshID = '700821' #TESTNO" , Oslo: 109979, Bodø: 700821 -->
<!-- userRole <-'SC' #'CC' , 'LC', 'LU' -->
<!-- ``` -->

\pagebreak

# Antall pasienter

* Totalt
* Over tid
* Per enhet

\pagebreak

# Antall registreringer

* Totalt
* Over tid
* Per enhet


## Antall registreringer per enhet
```{r}
myInData <- DL$RegData2
RegDataNatVal_filtered2019 <- norspis2::fun3_1_filter_RegData(RegData = myInData,
                                                              regStatus = c(1),
                                                              regType = c(1,2,3,4,5,6,98,99),
                                                              dateFrom = "2020-01-01",
                                                              dateTo = "2020-12-31",
                                                              ageFrom = 0,
                                                              ageTo = 200)

tab <- norspis2::make_table_DQ_regCount(RegDataNatVal_filtered2019)

ft <- norspis2::make_table_DQ_regCount_asFt(tab)

ft

```

\pagebreak

## Antall registreringer per avdeling per år

Startregistreringer

```{r}
  #START
  #filter data for e.g. 2012-2019
  RegDataNatValFiltered <- fun3_1_filter_RegData(RegData = DL$RegDataNatVal2 ,
                                                 regStatus = c(1),
                                                 regType = c(1,2,3,4),#START
                                                 dateFrom = "2012-01-01",
                                                 dateTo = "2021-12-31",
                                                 ageFrom = 0,
                                                 ageTo = 200)

  norspis2::make_table_DQ_regCountYearly(RegDataNatValFiltered = RegDataNatValFiltered)
  
  

```

\pagebreak

Sluttregistreringer

```{r}
#END
  #filter data for e.g. 2012-2019
  RegDataNatValFiltered <- fun3_1_filter_RegData(RegData = DL$RegDataNatVal2 ,
                                                 regStatus = c(1),
                                                 regType = c(5,6,98,99),#END
                                                 dateFrom = "2012-01-01",
                                                 dateTo = "2021-12-31",
                                                 ageFrom = 0,
                                                 ageTo = 200)

  norspis2::make_table_DQ_regCountYearly(RegDataNatValFiltered = RegDataNatValFiltered)
```


# Antall registreringer 


# Resultater

## Kvalitetsindikatorene over tid, nasjonalt og per avdeling

```{r}

#filter data for e.g. 2012-2019
RegDataStartEndNatValFiltered <- norspis2::fun3_2_filter_RegDataStartEnd(
                                  RegDataStartEnd = DL$RegDataStartEndNatVal2,
                                  BasisRegStatus.x = c(1),#c(0,1,-1),
                                  BasisRegStatus.y = c(1),#c(0,1,-1,NA)
                                  RegRegType.x = c(0,1,2,3,4,5,6,98,99),
                                  RegRegType.y = c(5,6,98,99,NA),
                                  dateFrom.x = "2012-01-01",
                                  dateTo.x = "2100-12-31",
                                  dateFrom.y = "2012-01-01",
                                  dateTo.y = "2020-12-31",
                                  ageFrom.x = 0,
                                  ageTo.x = 200,
                                  ageFrom.y = 0,
                                  ageTo.y = 200)
                                  
 # tableToFig <- make_figTable_unitCompar(myIndata_NatVal = RegDataStartEndNatValFiltered,
 #                                        myInvar01 = "EDEQ60GlobalScore_CHANGE_PROP")

 
 library(directlabels)
  
RegDataStartEndNatValFiltered_summarized <- RegDataStartEndNatValFiltered %>%
  #group_by together with summarize (see Wickham, R for Data Science)
  dplyr::group_by(Year.y,AvdNavn)%>%
    dplyr::summarize(perc = mean(EDEQ60GlobalScore_CHANGE_PROP, na.rm = T),#mean() of 0-1 gives
                                                          #proportion
                     n = sum(!is.na(EDEQ60GlobalScore_CHANGE_PROP)))

# %>%
#  
#     #When perc is between 0-1 we multiply by 100, else we keep the perc value
#     #(which will then be a mean ordinary mean value):
#     dplyr::mutate(perc = dplyr::case_when(perc >= 0 &
#                                             perc <= 1 ~ perc*100,
#                                           TRUE ~perc)) %>%
#     #makes hospital names include "n":
#     dplyr::mutate(AvdNavn = paste0(AvdNavn, ' (', n,')' )) %>%
#     #removes hospitals w n<20 (choose 0.00000123 as easy identifiable value
#     dplyr::mutate(perc = ifelse(n<5, 0.00000123, perc)) %>%
#     dplyr::mutate(!!myInvar01 := 0)%>%
#     #create new variable with name same as myinVar name, and set the values
#     #equal to name of 4. columns whic is the new myInvar01 column:
#     dplyr::mutate(!!myInvar01 := (colnames(.[,4])))%>%
#     #recode nan - choose 0.00000123 (as above for units with N<5):
#     dplyr::mutate(perc = dplyr::case_when(is.nan(perc) ~ 0.00000123,
#                             TRUE ~ perc))
# 
#   #SORT (from smallest to largest proportions)
#   ## forcats needed to reorder the levels (as a means to SORT the variable):
#   myInData_NatVal_summarized$AvdNavn <-
#     myInData_NatVal_summarized$AvdNavn %>%
#     forcats::fct_reorder(myInData_NatVal_summarized$n,
#                          .desc=F) %>%
#     forcats::fct_reorder(myInData_NatVal_summarized$perc,
#                          .desc=F)#T for the other order
# 
#   ## Then we first sort by N and then by percentage
#   myInData_NatVal_summarized <- myInData_NatVal_summarized %>%
#     dplyr::arrange(n) %>%
#     dplyr::arrange(perc)



ggplot2::ggplot(data = RegDataStartEndNatValFiltered_summarized,
       mapping = aes(x = Year.y, y = perc, color = AvdNavn, fill=AvdNavn)
       ) +
  scale_x_continuous(expand = expansion(mult = c(0, .25))) +
  geom_area(aes(fill = AvdNavn, group = AvdNavn),
            alpha = 0.25, position = 'identity',
            show.legend = F)+
  geom_line(show.legend = F)+
  geom_point(show.legend = F)+
  geom_dl(aes(label = AvdNavn), method = list("last.bumpup", cex = 0.7))+
  theme_bw()+
  ylab("Andel (prosent)")+
  xlab("År")+
  scale_color_manual(values=c("Nasjonal" = "black"))


#a "spread" table of the data we use in the plot
perc <- RegDataStartEndNatValFiltered_summarized %>%
          select(-n)%>%
          tidyr::spread(key=Year.y, value = perc)


n <- RegDataStartEndNatValFiltered_summarized %>%
          select(-perc)%>%
          tidyr::spread(key=Year.y, value = n)


```




